/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VoteIndexRouteImport } from './routes/vote/index'
import { Route as GovernanceIndexRouteImport } from './routes/governance/index'
import { Route as EarningsIndexRouteImport } from './routes/earnings/index'
import { Route as DatasetsIndexRouteImport } from './routes/datasets/index'
import { Route as ContributeIndexRouteImport } from './routes/contribute/index'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VoteIndexRoute = VoteIndexRouteImport.update({
  id: '/vote/',
  path: '/vote/',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceIndexRoute = GovernanceIndexRouteImport.update({
  id: '/governance/',
  path: '/governance/',
  getParentRoute: () => rootRouteImport,
} as any)
const EarningsIndexRoute = EarningsIndexRouteImport.update({
  id: '/earnings/',
  path: '/earnings/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsIndexRoute = DatasetsIndexRouteImport.update({
  id: '/datasets/',
  path: '/datasets/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributeIndexRoute = ContributeIndexRouteImport.update({
  id: '/contribute/',
  path: '/contribute/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contribute/': typeof ContributeIndexRoute
  '/datasets/': typeof DatasetsIndexRoute
  '/earnings/': typeof EarningsIndexRoute
  '/governance/': typeof GovernanceIndexRoute
  '/vote/': typeof VoteIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contribute': typeof ContributeIndexRoute
  '/datasets': typeof DatasetsIndexRoute
  '/earnings': typeof EarningsIndexRoute
  '/governance': typeof GovernanceIndexRoute
  '/vote': typeof VoteIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contribute/': typeof ContributeIndexRoute
  '/datasets/': typeof DatasetsIndexRoute
  '/earnings/': typeof EarningsIndexRoute
  '/governance/': typeof GovernanceIndexRoute
  '/vote/': typeof VoteIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contribute/'
    | '/datasets/'
    | '/earnings/'
    | '/governance/'
    | '/vote/'
    | '/api/auth/$'
    | '/api/rpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contribute'
    | '/datasets'
    | '/earnings'
    | '/governance'
    | '/vote'
    | '/api/auth/$'
    | '/api/rpc/$'
  id:
    | '__root__'
    | '/'
    | '/contribute/'
    | '/datasets/'
    | '/earnings/'
    | '/governance/'
    | '/vote/'
    | '/api/auth/$'
    | '/api/rpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContributeIndexRoute: typeof ContributeIndexRoute
  DatasetsIndexRoute: typeof DatasetsIndexRoute
  EarningsIndexRoute: typeof EarningsIndexRoute
  GovernanceIndexRoute: typeof GovernanceIndexRoute
  VoteIndexRoute: typeof VoteIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vote/': {
      id: '/vote/'
      path: '/vote'
      fullPath: '/vote/'
      preLoaderRoute: typeof VoteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance/': {
      id: '/governance/'
      path: '/governance'
      fullPath: '/governance/'
      preLoaderRoute: typeof GovernanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earnings/': {
      id: '/earnings/'
      path: '/earnings'
      fullPath: '/earnings/'
      preLoaderRoute: typeof EarningsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/': {
      id: '/datasets/'
      path: '/datasets'
      fullPath: '/datasets/'
      preLoaderRoute: typeof DatasetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribute/': {
      id: '/contribute/'
      path: '/contribute'
      fullPath: '/contribute/'
      preLoaderRoute: typeof ContributeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContributeIndexRoute: ContributeIndexRoute,
  DatasetsIndexRoute: DatasetsIndexRoute,
  EarningsIndexRoute: EarningsIndexRoute,
  GovernanceIndexRoute: GovernanceIndexRoute,
  VoteIndexRoute: VoteIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
