[package]
name = "quorum"
version = "0.0.1"

[addresses]
quorum = "0x25b6fd2cd3e4d22c78e680cc125b0ef7bbf298e75c708e9908dc27ade6f4d693"

[dev-addresses]
quorum = "0x25b6fd2cd3e4d22c78e680cc125b0ef7bbf298e75c708e9908dc27ade6f4d693"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
