[package]
name = "quorum"
version = "0.0.1"

[addresses]
quorum = "0x6e039fce5be1a646bf6ec7b86821a0f2137f60dabb36e1b6dc0e16d1f931f48d"

[dev-addresses]
quorum = "0x6e039fce5be1a646bf6ec7b86821a0f2137f60dabb36e1b6dc0e16d1f931f48d"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
